ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.techno90s.online
CATALOGUE_HOST: catalogue-dev.techno90s.online
REDIS_HOST: redis-dev.techno90s.online
USER_HOST: user-dev.techno90s.online
CART_HOST: cart-dev.techno90s.online
MYSQL_HOST: mysql-dev.techno90s.online
SHIPPING_HOST: shipping-dev.techno90s.online
RABBITMQ_HOST: rabbitmq-dev.techno90s.online
PAYMENT_HOST: payment-dev.techno90s.online